### ISSUE TITLE
Bug: Picture is overlaid by picture

### ISSUE THREAD

**Issue by HotarunIchijou** [nullxception/boorusphere#101]
### Type

UI-related issues

### Bug description

I find it accidentally. 

### Steps to reproduce

1. Zoom the picture by double tapping
2. Swipe to the next image
3. Go back to the previous image
4. You can try to reproduce it repeatedly, one time it will appear

### Android version

Android 13

### App version

Booruspere v1.3.2

### Screenshots or videos

![](https://user-images.githubusercontent.com/113282550/223126417-7aed583e-f72b-41cf-b9d7-27a70729e2fd.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by HotarunIchijou** [comment]
Yeah, it happens sometimes
Also note that the other image disappears, but it disappears slowly (about 1 second) so I think that's the reason

**Comment by nullxception** [comment]
I can't really reproduce the issues (even a single time), so I can't debug and fix it.
