### ISSUE TITLE
Bug: big video isn't playing

### ISSUE THREAD

**Issue by HotarunIchijou** [nullxception/boorusphere#102]
### Type

Other

### Bug description

Find it accidentally

### Steps to reproduce

Play any video that bigger 1 minute, I think

### Android version

Android 13

### App version

Boorusphere v1.3.3

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by nullxception** [comment]
The video player is works fine even on long video format, it just that it doesn't retry or have a error message when it failed to load the video, so it's more of connection issues.

**Comment by HotarunIchijou** [comment]
No, it doesn't. I don't have any connection issues, and on sites video works fine, while in app it just doesn't load

**Comment by nullxception** [comment]
> No, it doesn't. I don't have any connection issues, and on sites video works fine, while in app it just doesn't load

browsers can stream video in real time, this app doesn't, so it has to load the video fully before it can plays, and the video fetcher is currently nowhere near stable at all.

**Comment by nullxception** [comment]
you guys don't know how bad the current state of video player on flutter right now.
[`better_player`](https://github.com/jhomlala/betterplayer) is not maintained and broken.
and the official [`video_player`](https://pub.dev/packages/video_player) package that we use today is too basic (it can't even cache video that is loaded from the network, yes, that's ridiculous. but we managed to do it here somehow).

**Comment by HotarunIchijou** [comment]
OK
