### ISSUE TITLE
Bug: Gelbooru "safe" tag is "general"

### ISSUE THREAD

**Issue by Riven-Spell** [nullxception/boorusphere#104]
### Type

UI-related issues

### Bug description

By default, BooruSphere appears to provide `rating:safe` instead of `rating:general` for Gelbooru's safety tags. `rating:safe` does not exist on Gelbooru, and is instead equivalent to `rating:general`.

### Steps to reproduce

1. Open Gelbooru
2. Search for favorite anime girl
3. Hit ratings, safe

### Android version

Android 13

### App version

Boorusphere 1.3.3

### Screenshots or videos

Picking a rating:
![Picking a rating](https://user-images.githubusercontent.com/13892402/223574750-c9e0c604-74a3-4a4e-b4a5-7aae86134954.png)

The provided "safe" rating:
![No results](https://user-images.githubusercontent.com/13892402/223574810-13cfa9b5-f0bc-4ef6-b9e0-fccebcdcb7b2.png)

Providing "general" manually:
![Results!](https://user-images.githubusercontent.com/13892402/223574850-ed33c082-cc17-4956-8434-ae6958aca326.png)

### Solution

Temporary workaround: supply `rating:general` manually

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by nullxception** [comment]
Site a uses x, b uses y, then there's a new rating value for another site, so on and so forth.
There'll be no end for this kind of thing, so nope no more rating option, thanks.

**Comment by Riven-Spell** [comment]
> Site a uses x, b uses y, then there's a new rating value for another site, so on and so forth. There'll be no end for this kind of thing, so nope no more rating option, thanks.

Perhaps make it configurable?

**Comment by nullxception** [comment]
> Perhaps make it configurable?

that's even worse.

The point is to be consistent and fair. rating: safe should give `rating:safe` result just like in the browser, if the particular booru doesn't give any result, then there's no post that rated as safe on the server.
