### ISSUE TITLE
Bug: Vinebooru gives no results

### ISSUE THREAD

**Issue by jschenke488** [nullxception/boorusphere#105]
### Type

Booru parser issues

### Bug description

Adding https://booru.vineshroom.net/ works, but no results are ever returned

### Steps to reproduce

- Add https://booru.vineshroom.net/
- Check results of any search

### Android version

Android 13, OneUI 5.1

### App version

1.3.3

### Solution

It may be possible that ratings are causing the bug because as far as I know, Vinebooru doesn't have ratings

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by jschenke488** [comment]
If it is in fact ratings, maybe add an option to disable ratings for a specific server?

**Comment by nullxception** [comment]
> It may be possible that ratings are causing the bug because as far as I know, Vinebooru doesn't have ratings

I don't think so.
on me, the server scanner can't even find the proper search query.

![image](https://user-images.githubusercontent.com/58150791/224467377-da08541f-34c8-487d-9b75-0bae5f7c71e3.png)

**Comment by nullxception** [comment]
I tried manually go to shimmie search api on it : https://booru.vineshroom.net/api/danbooru/find_posts/index.xml 
and got 404 not found, so we need to find the right search query

**Comment by nullxception** [comment]
looks like the site disable their support for external API, so there's nothing we can do about that
