### ISSUE TITLE
Feature: ability to randomize order of search results

### ISSUE THREAD

**Issue by WasmachenDennSachenSo** [nullxception/boorusphere#106]
### Type

Functionality

### Issue

For most boorus, there is currently no way to achieve that.

### Feature

This would be great to just casually look around for new stuff with specific tags but with random order every time you hit the search button.

Maybe in form of a toggle at the location of the filter options.

SankakuComplex has a random search order.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by nullxception** [comment]
> For most boorus, there is currently no way to achieve that.

Then why even bother ?
