### ISSUE TITLE
Feature: Preview quality

### ISSUE THREAD

**Issue by ksvijay1** [nullxception/boorusphere#108]
### Type

UI improvement

### Issue

Cant see the preview in quality it is slightly blury

### Feature

Option to see the preview in original quality or sample qualty

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by nullxception** [comment]
duplicated #20
