### ISSUE TITLE
Feature: rule34hentai.net support

### ISSUE THREAD

**Issue by someshittyeletronicmusicband** [nullxception/boorusphere#109]
### Type

Functionality

### Issue

Nothing happens when I add the website.

### Feature

It would be great if it was supported.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by nullxception** [comment]
looks like the site disable their support for external API
