### ISSUE TITLE
Feature: Sign into buroou sites

### ISSUE THREAD

**Issue by Qwerty6566** [nullxception/boorusphere#111]
### Type

Functionality

### Issue

I can't see my favorites on my account, plus I can't go past the built in blacklist

### Feature

Being able to sign in would have you be able to add your pre-existing favorites, as well as being able to bypass the blacklist on sites, like e621

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by nullxception** [comment]
Sign-in or API keys support is out of this app coverage, it just too complicated to handle wide-variety of booru APIs
