### ISSUE TITLE
Scrolling becomes progressively choppier with scrolling down the page

### ISSUE THREAD

**Issue by infinitieunique** [nullxception/boorusphere#118]
### Type

UI-related issues

### Bug description

Scrolling animation begins to stutter when you scroll down the page for some time . Happens each time you scroll down the page for long enough (not so long).  The issue disappears when you restart the application, but then comes back when. Seems like it has to do with loading roo many images (may cause memory leakage)

### Steps to reproduce

1. Open application.
2. Scroll down for some time

### Android version

11

### App version

1.3.7

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by nullxception** [comment]
sorry but it's pretty much a side effect of having multiple backstack (where you can go back to previous searches continuously until it goes to the first state).

**Comment by nullxception** [comment]
I've been telling this to people before, that keeping the page state across searches is not a cheap thing and will impact performance, and instead they're accusing me for many things instead.

and now what ? memory leak ? 
nah bro, the right term is simply a "high memory usage".

**Comment by infinitieunique** [comment]
> I've been telling this to people before, that keeping the page state across searches is not a cheap thing and will impact performance, and instead they're accusing me for many things instead.
> 
> and now what ? memory leak ? 
> nah bro, the right term is simply a "high memory usage".
> 

I understand that this might not necessarily be an unintentional thing, but then don't you think it would be reasonable to at least make a setting to turn it off or make a fork without this "feature". Don't you think that if it causes problems even on my (pretty much) high end phone (OnePlus 9RT, s888 + 12GB) then users of lower end devices might experience severe lag that completely (yes, exactly "completely", because for any sane user if IT lags then nothing else matters) ruins the experience. I can not do what I am typically doing in any other application: infinitely scroll down without experiencing any lag. Needless to say that smoothness and glitchlessness should be #1 priority for every developer

**Comment by nullxception** [comment]
> I understand that this might not necessarily be an unintentional thing, but then don't you think it would be reasonable to at least make a setting to turn it off or make a fork without this "feature". 

ah here we go again, everything can be a "settings".
don't you know that a setting for "blurring an explicit content" itself makes half part of the thumbnail ui code slower and harder to maintain ?
people think by disabling the settings, the code is magically gone. no, it just makes it more complicated.

Currently I still working on fixing the performance of this app that caused by multi backstack, such as video player is still playing even when we already moving to a different page.

It's pretty hard to working on a code that nobody even interested, you know (most people that contributes here is more of translating rather than the actual code). So if there's anyone want to forks and playing with the code too, I'd be more than happy to welcome.

**Comment by infinitieunique** [comment]
I appreciate your effort and I can say that this is one of the best booru browsers I have ever used, but you have to understand that UI frame rate consistency and abscence if stutters should be #1 priority. Do you think it matters that the meal is tasty if it isn't properly cooked/half-ready? Without any disrespect for your work I am asking you to concentrate your efforts on fixing the stutter issue
