### ISSUE TITLE
Inapp updater bug

### ISSUE THREAD

**Issue by rinme** [nullxception/boorusphere#119]
### Type

UI-related issues

### Bug description

Inapp updater is download the apk but not install.

### Steps to reproduce

1. Open information
2. Download update

### Android version

Android 11

### App version

1.3.8
And probably 1.3.9 wouldn't fix

### Screenshots or videos

![Screenshot_20230530-224847](https://github.com/nullxception/boorusphere/assets/56862783/457d7768-d3c4-49a1-8960-793cac077798)
![Screenshot_20230530-224851](https://github.com/nullxception/boorusphere/assets/56862783/0f18738d-d044-4afa-8c20-344351989fc6)

### Solution

Add the prompt to ask if want to install now to open system installer prompt (I knew it sounds more step for ux), Or maybe unlock the notification to able to press to install in case the auto install is messed.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by nullxception** [comment]
does it happen only when device is unlocked ?
cause currently there's no way to add functionality to the download notification (flutter downloader thing).

**Comment by rinme** [comment]
> does it happen only when device is unlocked ?
> cause currently there's no way to add functionality to the download notification (flutter downloader thing).
> 

Yes, It happened both unlocked and locked. The app can't get the installer if have multi installer (I guess, aka SAI)

**Comment by nullxception** [comment]
> > does it happen only when device is unlocked ?
> > cause currently there's no way to add functionality to the download notification (flutter downloader thing).
> 
> Yes, It happened both unlocked and locked. The app can't get the installer if have multi installer (I guess, aka SAI)

ah I see what's happening, thanks for clarifying

**Comment by sam-gq** [comment]
I have the same thing when using built-in updater but it's a minor complaint when using this. There is no option to change location to _/Download_ folder of downloaded apk to update the app.

But instead, the apk stored inside the app data which I can't find the downloads folder and delete the downloaded apk or even clear cache the app to free up space before I forgot to update the app. So I ended up to clear data this app, restore my progress and tried to update again.

Do you have any consideration @nullxception, storing updated apk files to the downloads folder? It is the first time to comment in this project.

**Comment by nullxception** [comment]
> I have the same thing when using built-in updater but it's a minor complaint when using this. There is no option to change location to _/Download_ folder of downloaded apk to update the app.
> 
> But instead, the downloaded apk stored inside the app data can't be deleted or even clear cache the app to free up space when before I forgot to update the app. So I ended up to clear data this app, restore my progress and tried to update again.
> 
> Do you have any consideration @nullxception, storing updated apk files to the downloads folder instead of the in-app data itself? It is the first time to comment in this project.

Uhm, the app already does that for you. The app will be downloading the apk to app cache first, and then when update completed, it's automatically moved to /sdcard/Download/Boorusphere/app-update/ folder.

The actual bug on 1.3.8 and 1.3.9 is, the [app_updater](https://github.com/nullxception/boorusphere/blob/main/lib/presentation/provider/app_updater.dart) is not properly connected to the flutter_downloader API.
so even if the apk download has been performed, the app just doesn't get any information about it at all, it's like nothing happens.

It's fixed on 1ac3ea9731082e809195ebf7102530a9b82b88d3 already, so next release should be fine.
