### ISSUE TITLE
ARMv8 binaries on IzzyOnDroid

### ISSUE THREAD

**Issue by flippette** [nullxception/boorusphere#120]
### Type

Other

### Issue

Is it possible to provide 64 bit binaries on the izzy repos?

### Feature

64 bit binaries on the izzy repos

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.

**Comment by nullxception** [comment]
After lurking at [IzzyOnDroid:repo/issues](https://gitlab.com/IzzyOnDroid/repo/-/issues), looks like Izzy pick armv7a for compatibility reason, so ... is it what it is.
