### ISSUE TITLE
Feature: Szurubooru support

### ISSUE THREAD

**Issue by LukachoLombardi** [nullxception/boorusphere#121]
### Type

Functionality

### Issue

Basically what the title says. Szurubooru is a booru flavour often used for sfw communities. There is no compatible app yet, even though their API is really well documented.

### Feature

This app looks great and I think both sides would benefit greatly from a mobile app implementing this board flavour. I assume different API-specs are handled through different abstractions exposing the same methods, so doing this for a new API should be possible.

### Additional context

You can can find their API docs on their GitHub repo, which shouldn't be hard to find.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.

**Comment by nullxception** [comment]
great api documentation, do you have an example of site that uses this ?
preferably more than one site, for testing purposes.

**Comment by LukachoLombardi** [comment]
> great api documentation, do you have an example of site that uses this ?
> preferably more than one site, for testing purposes.

The booru I was using got spontaneously shut down yesterday but I'll see if I can find other ones. They're mostly not indexed by Google and the only one I could find has contents I don't really wanna share on GitHub. But I'll see if I can find more!

**Comment by LukachoLombardi** [comment]
Found a Homestuck one:
https://homestuck.net/resources/booru/posts

**Comment by nullxception** [comment]
Szuru api is pretty well documented, but it's so different/non-standard, and pretty limited as well (compared to regular danbooru/moebooru).

And sadly getting tags.json needs an user account, so search suggestion wouldn't be working out-of-the box.
