### ISSUE TITLE
Bug: Swipe not working if you swipe it fast enough

### ISSUE THREAD

**Issue by uzuki-P** [nullxception/boorusphere#122]
### Type

UI-related issues

### Bug description

On the image viewer, if you swipe it fast enough the swipe will not working until wait a couple of second. I suspect it's waiting for the swipe animation to finish first OR waiting download the next image to finish.

### Steps to reproduce

1. View an image
2. Swipe it fast enough

### Android version

13

### App version

1.4.0

### Screenshots or videos

https://github.com/nullxception/boorusphere/assets/16524713/5ad2100a-f73b-4e3b-b7c7-a8f9931abc2d

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by nullxception** [comment]
Pretty sure it's device issues, it works perfectly fine on my phone.

https://github.com/nullxception/boorusphere/assets/58150791/6b35cf10-081b-4be8-84e5-d589f044d03d
