### ISSUE TITLE
Bug: Unable to download pictures

### ISSUE THREAD

**Issue by jerrychen007** [nullxception/boorusphere#125]
### Type

UI-related issues

### Bug description

Hello, I've noticed that I'm unable to download certain images from Yande.re no matter how many times I try. The screenshots indicate that the downloads failed without providing any specific reason.
Thank you for your attention.

### Steps to reproduce

The error seems to occur randomly. I tested the app on another phone (Android 10), and the 'broken' images were downloadable.

### Android version

13.1

### App version

1.4.0

### Screenshots or videos

![Screenshot_20230625-190333~01](https://github.com/nullxception/boorusphere/assets/28459583/ae168b20-bb34-436b-ac34-30e0b6821899)
![Screenshot_20230625-192518_Boorusphere~01](https://github.com/nullxception/boorusphere/assets/28459583/7f179c75-658b-4f83-a2a9-580378c19991)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by jerrychen007** [comment]
After conducting some tests, I have discovered that every image file name that fails to download contains the character colon ":". I hope this information can be helpful.

**Comment by nullxception** [comment]
> 



> After conducting some tests, I have discovered that every image file name that fails to download contains the character colon ":". I hope this information can be helpful.

Thanks! I tried on my phone and it's failed too.
