### ISSUE TITLE
How do I add Realbooru?

### ISSUE THREAD

**Issue by bone-grinder28** [nullxception/boorusphere#126]
### Type

Other

### Bug description

This isn't a bug but a genuine question. When I add the website to Boorusphere the query section is not automatically filled when the site is chosen, I do not know where to get the information for "Search Query", "Tag Suggestion" and "Web Post Query".

### Steps to reproduce

Step 1: Add Server

Step 2: Add Realbooru.com

Step 3: Query Section is not automatically filled with the search information as it does with other websites.

### Android version

Android Version 8.1.0

### App version

Latest Version

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by nullxception** [comment]
after few inspection, looks like there's a bug on realbooru where they won't reply with anything when limit query is set below 20.
we can fix it by scanning realbooru with limit query above 20.
