### ISSUE TITLE
Multi Booru Search

### ISSUE THREAD

**Issue by GlowScarf** [nullxception/boorusphere#129]
### Type

Functionality

### Issue

More variation

### Feature

Fetch results from different boorus

### Additional context

Similar option to Lolisnatcher

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.

**Comment by nullxception** [comment]
sorry, it is designed to handle only one server per search session for simplicity and straightforwardness, so adding such thing would require a lot of refactoring on both architectural and UI as well.
it's not as simple as "just perform a search on multiple boorus and combine the result".
