### ISSUE TITLE
Downloads Section Improvents and Fixes (after v1.1.1)

### ISSUE THREAD

**Issue by maisans-maid** [nullxception/boorusphere#13]
The download section was a whole lot better after the recent update, tho there are some things that i'd love to see be improved (sorry, but i really love using this app so i thought i had to suggest inputs):

1. When grouped by servers, the servers should be collapsable (useful for cases where there's too many images that have been downloaded). Clicking the server name on download would toggle the collapse state of that particular section. Also, i think it's be better to have them at hidden state on default when the number of downloaded files exceeds a set number, with a badge indicating how many images were downloaded for that server when on hiddena state. 

2. Downloaded images could use a filter option to filter downloaded images by available tags (user can select which tag/s to include), also with multiple tags selected, an option whether to use "or" and "and" for them.

3. Downloaded images should not be ~~viewable by~~ present in any gallery app (or at least have the option to make it viewable or hidden on other image/video viewer app, tho it is preferred to be hidden).

4. Use a check mark icon instead of the `downloaded` string as an indicator that the image has been downloaded. Similarly, the "downloading" string indicating the file is currently being downloaded could use an animated icon as well. Could also just make the string a less saturated color than the one used for the file name (i.e. gray)

However, there are also some things i think are bugs on that section, such as:

1. Deleting the downloaded image from the file manager does not update the downloads list section of the app. Clicking on the image instead gives an unknown error, or "File might be corrupted" error when opened via gallery app.

![Screenshot_2022-07-27-15-10-19-684_com.miui.videoplayer.jpg](https://user-images.githubusercontent.com/56829176/181184586-d935a092-0a89-4077-9393-007b7853c1f2.jpg)

Suggested fixes:
1. Deleted images will be indicated on the downloads section with a red "x" or "i" icon. An option to "redownload removed files" and "remove deleted files from list" could be added.

2. App will not show deleted files on the download page.

P.S. Thanks for the recent update, loved them!

**Comment by nullxception** [comment]
> When grouped by servers, the servers should be collapsable (useful for cases where there's too many images that have been downloaded). Clicking the server name on download would toggle the collapse state of that particular section. Also, i think it's be better to have them at hidden state on default when the number of downloaded files exceeds a set number, with a badge indicating how many images were downloaded for that server when on hiddena state.

nice idea. for that, looks like I have to make a custom list view instead of rely on [grouped_list](https://pub.dev/packages/grouped_list) since it has no option to do that.

> Downloaded images should not be ~viewable by~ present in any gallery app (or at least have the option to make it viewable or hidden on other image/video viewer app, tho it is preferred to be hidden).

technically it's possible (by adding file `.nomedia` to the directory), we have just to make it an option for it.
Reference: https://medium.com/@mutiakun/getting-know-about-nomedia-files-on-android-a51068430e38

> Use a check mark icon instead of the `downloaded` string as an indicator that the image has been downloaded. Similarly, the "downloading" string indicating the file is currently being downloaded could use an animated icon as well. Could also just make the string a less saturated color than the one used for the file name (i.e. gray)

nice ones! simple yet still informative.

> Deleted images will be indicated on the downloads section with a red "x" or "i" icon. An option to "redownload removed files" and "remove deleted files from list" could be added.

Yeah, I prefer this since it's more informative than just clearing the downloaded entry (also helpful in case we as users accidentally delete the file from gallery or file manager).

**Comment by nullxception** [comment]
> sorry, but i really love using this app so i thought i had to suggest inputs

noo don't be sorry, feedback is the one who make app better.
I love and welcome to people feedbacks even tho I can't resolve the issues everytime 😂.

**Comment by nullxception** [comment]
For filtering download by tags, I'm not going to implement it as it's not intuitive from UX standpoint, maybe I'll add a search bar on the download page instead just like google chrome do.

I'll close this issues manually.
