### ISSUE TITLE
Bug: Error installing Boorusphere, unsupported ABIs

### ISSUE THREAD

**Issue by Kusoneko** [nullxception/boorusphere#130]
### Type

Other

### Bug description

This is a bit of a complicated bug to describe:

I have Boorusphere installed onto my Pixel 5, running LineageOS 20 (aka Android 13), it seems to work fine. I have recently upgraded to a Pixel 7 Pro, which is also running LineageOS 20. Unfortunately, I cannot seem to install Boorusphere on this one at all. I am definitely not going to walk around with 2 phones for the few apps that refuse to install on the new phone, however, I figured since this app is in active development, I might as well try to figure out why it refused to install so that perhaps the issue can be resolved. At first it would just say it's incompatible and error out without a message when trying to install it, but that's not very helpful. I somehow managed to get an error code and error message while trying to install it this last time though. It says:

```
Error installing Boorusphere

Error -113: The system failed to install the package because its packaged native code did not match any of the ABIs supported by the system.
```

While this is a bit clearer about what the issue is, it isn't exactly obvious how to fix this, however, as I have the device, I might as well offer to try and install test versions to see if we can't figure out how to "match a supported ABI", if you're interested in trying.

### Steps to reproduce

Step 1. Have a Pixel 7 Pro
Step 2. Install F-Droid
Step 3. Go into F-Droid settings and allow seeing incompatible apps
Step 4. Search for Boorusphere and install it
Step 4.1. Actually Step 4 failed
Step 5. ??? (I have no clue why the next time I got a clearer error message)
Step 6. Retry the installation later and get the error message above

### Android version

LineageOS 20 (Android 13)

### App version

1.3.9, 1.4.0 and 1.4.1 (they're the only ones I can see on F-droid)

### Screenshots or videos

I really don't think a screenshot or video of a phone refusing to install an app is very helpful beyond the error message which I typed up above.

### Solution

Possible solutions:
1. Figure out the ABIs supported by the app, and the ABIs supported by my device, and figure out how to make the app support at least 1 ABI supported by my device?
2. Not try to support this newer phone at all.

### Additional context

Thanks for any help,
Kusoneko.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Kusoneko** [comment]
Okay, I've been looking it up in even more details, and I think it's possible this issue should be going even further upstream, as the so-called ABIs are actually the CPU instruction sets supported by the device;

There is the now defunct armeabi which is apparently armv5TE, then there is armeabi-v7a which is armv7a, which is slowly dying out as it's the last 32-bit version, then there's armv8a, which is the first 64-bit version, which also tends to have a few cores that can read armv7a. The problem is actually that the Pixel 7 Pro uses armv9a and thus only supports armv8a and armv9a. Though, that still doesn't explain why it doesn't install the app though, cause as far as I can tell it should run just fine on armv8a?

Anyways, I should go sleep before I think more, cause it's almost 2AM for me.

**Comment by sebastien46** [comment]
The F-Droid build of the app only supports armv7a, hence why it's not compatible with armv8/9 only phones like the Pixel 7 Pro (can confirm as I use a Pixel 7).
See #120 for reference.

**Comment by IzzySoft** [comment]
> Asking @IzzySoft to provide the other ABIs in his repo (some apps from there support armv8a, so I'd venture a guess that it's possible, he's just not doing it for this specific app?)

Nope. My repo supports only 1 APK per release. Plus there's a size limit (30 MB per app). So the only alternative would be switching to an "universal APK" (one covering multiple ABIs) at the price of less versions being available simultaneously (as less would fit into the 30 MB limit) – or to switch to the arm64 build, thus dropping support for all 32bit devices in favor of the 1 Pixel (there will be more 64bit-only-devices coming up the next years due to ARM dropping 32bit support from their newer CPUs).

> Possibly requesting for the app to be included in the F-Droid main repo if at all possible, which would help as they tend to build it with support for all ABIs they can get I think?

Viable option. And I'd say the app should meet the criteria (my scanner at least sees no issues, but it only scans the APK – so I did not check if there are any "blobs" that might cause issues), so it would be worth a try. Opening an RFP is easy – and from there we can see what F-Droid's issuebot states.

**Comment by Kusoneko** [comment]
@nullxception I've created a request for adding the app to f-droid, if you're not opposed to it, I could tick that box too. Btw, you can check it real quick if you have time to be sure I didn't miss anything: https://gitlab.com/fdroid/rfp/-/issues/2468

Thank you for this app!

@IzzySoft I can't seem to add the tags to it like in other requests such as in-izzysoft in-github-releases and so on? Probably done automatically or requires contributor rights of some sort I guess? The only thing I'm pondering about is the app id requiring domain name ownership, which I checked real quick and nic.io lists the chaldeaprjkt.io as not currently owned, not sure if this is fine or not? From looking at nullxception's github page, it seems like chaldeaprjkt is a github organization thing atm.

**Comment by IzzySoft** [comment]
The tags are automatically added by issuebot. To modify them (remove tags or adding more) requires at least "developer" status. I've just checked it as it flew into my inbox, complemented the YAML, left some comments – and added the "ready" label to mark it for packaging. It would be great if Flutter could be integrated here as submodule (for the reasons I pointed out there); that's not mandatory but strongly recommended.

Disclosure: I'm one of the F-Droid maintainers, which enabled me to deal with the tags. But not being an Android dev or Flutter expert, I must leave filling the gaps to someone else. If you can do that, I can help you with the next steps again. Should you need help for that yourself, just drop a note and I try to make some "wakeup calls" to my team members :wink:

Thanks for opening that RFP! Issuebot report looks as fine as I expected it to, no "show-stoppers" indicated.

**Comment by nullxception** [comment]
> @nullxception I've created a request for adding the app to f-droid, if you're not opposed to it, I could tick that box too. Btw, you can check it real quick if you have time to be sure I didn't miss anything: https://gitlab.com/fdroid/rfp/-/issues/2468

I'm okay with it, I'll check it real quick.
