### ISSUE TITLE
Opening booru links

### ISSUE THREAD

**Issue by infinitieunique** [nullxception/boorusphere#132]
### Type

Functionality

### Issue

The app neither won't show up in a system default link opening menu when opening a booru website not will allow you to type in the url address manually to open a booru picture

### Feature

At least add the url input box to type in the url manually and open up the pic in app, I hate doing things on my browser on mobile

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.

**Comment by nullxception** [comment]
this app access the booru api directly, it doesn't (and can't) parse the web page
