### ISSUE TITLE
Feature: chinese zh-Hans translation

### ISSUE THREAD

**Issue by History-exe** [nullxception/boorusphere#141]
### Type

Functionality

### Issue

Sorry for bothering you, I already done the zh-Hans translation. 
For some reason I can't push the code. But already sent the translation file to your email. Could you please check it and add the translation?

### Feature

Translation file please check the email 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.

**Comment by nullxception** [comment]
sure bro, I'll check that out

**Comment by nullxception** [comment]
Thanks!

**Comment by History-exe** [comment]
Thank you.
