### ISSUE TITLE
List of Additional Settings Suggestion

### ISSUE THREAD

**Issue by maisans-maid** [nullxception/boorusphere#15]
## General
- Select default start screen (which server to display)

## Notification
- Access notification settings within the app
- Set notification ringtone

## Cache
- Clear image cache
- Set maximum cache size

## Downloads
- Toggle button to display/hide download count badge (for unchecked/not yet viewed downloaded images on downloads section)
![IMG_20220731_224615.jpg](https://user-images.githubusercontent.com/56829176/182031803-817c7cd3-e959-43e6-94ed-f1e4c0c17a17.jpg)
- Toggle button to display download date (and an option to choose between actual or relative date)
![IMG_20220731_224918.jpg](https://user-images.githubusercontent.com/56829176/182031948-016f5af9-42bc-4d7c-a847-4ab5041e8495.jpg)
- Move download location to boorusphere dedicated folder by default (preferrably `storage/emulated/0/Boorusphere`) and add an option to select a custom location.
- Toggle button to warn users when attempting to download files larger than 10MB (or whatever you consider as "large files")

## Security
- Open links (location, source, etc.) in incognito mode (always by default). Can be changed via settings.
- Hide app content when switching between apps (Always, Never, Only when not in Safe Mode)

## Safe Mode
- Toggle mute explicit rated media on initial play (defaults to true, automatically mute explicit media when played for the first time)

## App Info
- Add `View Changelog` to view changelog for the current version
- Add `Something isn't working right` or `Report Bugs` that leads to the Submit Issue page of this repository.

Going to add more to this list in the future...

**Comment by nullxception** [comment]
> ## General
> 
>     * Select default start screen (which server to display)
> 

I don't like that, current implementation (start with last opened server) is already perfect (simple, no settings needed).

> ## Notification

Impossible to do with [`flutter_downloader`](https://pub.dev/packages/flutter_downloader).

>     * Clear image cache

Clear image cache is already implemented, see https://github.com/nullxception/boorusphere/commit/963c291634b68cb5bdba1b1b9246a2e5015ce59d .

>     * Set maximum cache size

[`extended_image`](https://pub.dev/packages/extended_image) has no option for that.

>     * Toggle button to display/hide download count badge (for unchecked/not yet viewed downloaded images on downloads section)

I don't like badge, it's intrusive.

>     * Toggle button to display download date (and an option to choose between actual or relative date)

Nice idea, but sadly we have no space left to display such things (I don't like having too complicated ui).

>     * Move download location to boorusphere dedicated folder by default (preferrably `storage/emulated/0/Boorusphere`) and add an option to select a custom location.

Impossible thanks to [scoped storage](https://developer.android.com/about/versions/11/privacy/storage) (android 11 privacy enhancements), only special app can do that (such as file managers or antivirus).

>     * Toggle button to warn users when attempting to download files larger than 10MB (or whatever you consider as "large files")

Another steps to just downloading a file ? big no.

>     * Open links (location, source, etc.) in incognito mode (always by default). Can be changed via settings.

Impossible to do.
We are just passing the link to the OS -> OS opens default/preferred browser or WebView.

>     * Hide app content when switching between apps (Always, Never, Only when not in Safe Mode)

It's possible on android, but not on flutter.
I'm not going to touch android-specific stuff.

>     * Toggle mute explicit rated media on initial play (defaults to true, automatically mute explicit media when played for the first time)

I don't accept any video related feature, video player alone is already complicated enough for me.

>     * Add `View Changelog` to view changelog for the current version

That's nice one, maybe I can add it.

>     * Add `Something isn't working right` or `Report Bugs` that leads to the Submit Issue page of this repository.

already think about that, but I'm not going to implement it anytime soon.

**Comment by nullxception** [comment]
FYI I don't like having too many options, it makes app complicated and resulting in fragile and buggy app.
but thanks for the suggestions anyway :)
I'll close this once `View Changelog` is implemented.

**Comment by maisans-maid** [comment]
> Another steps to just downloading a file ? big no.

Is it possible to indicate the file size in the details section of the image instead of a prompt? My device has small storage space so id like to have some sort of guide to compare which file to download (sampe or original) considering their file sizes.

**Comment by nullxception** [comment]
> > Another steps to just downloading a file ? big no.
> 
> Is it possible to indicate the file size in the details section of the image instead of a prompt? My device has small storage space so id like to have some sort of guide to compare which file to download (sampe or original) considering their file sizes.

it's not possible, some server only inform about original file size, others doesn't even have any file size at all.
