### ISSUE TITLE
please remember increasing versionCode when releasing

### ISSUE THREAD

**Issue by IzzySoft** [nullxception/boorusphere#2]
Just a note: the latest release (1.0.3) still has the same `versionCode` as the one before (`1001`). As that's what Android uses to tell versions apart, it won't show up as update for users. So please make sure to always increase that as well :wink: Thanks!

**Comment by nullxception** [comment]
Ah I see, I'll take a note for it!
Thanks for your great suggestions, IzzySoft 👍

**Comment by IzzySoft** [comment]
Gladly! Besides, on request your app became [available in my repo](https://apt.izzysoft.de/fdroid/index/apk/io.chaldeaprjkt.boorusphere) a month ago. You're welcome to [use my badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to link there from e.g. your Readme :smiley:

**Comment by nullxception** [comment]
> 
> 
> Gladly! Besides, on request your app became [available in my repo](https://apt.izzysoft.de/fdroid/index/apk/io.chaldeaprjkt.boorusphere) a month ago. You're welcome to [use my badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to link there from e.g. your Readme 😃

Awesome! I'll embed it on the readme real quick 😎

**Comment by IzzySoft** [comment]
Amazing: it's already there, cool! Thanks a lot!
