### ISSUE TITLE
low quality preview

### ISSUE THREAD

**Issue by BigDogg99** [nullxception/boorusphere#20]
Please increase quality of preview images 

![Screenshot_20220811-122139_Flexbooru](https://user-images.githubusercontent.com/109841554/184079164-26710186-250b-419f-b389-eddd8d4c46aa.png)

![Screenshot_20220811-122049_Boorusphere](https://user-images.githubusercontent.com/109841554/184079486-b5cd6b02-675b-49a9-a193-80f231f8e2f1.png)

**Comment by nullxception** [comment]
the quality of thumbnail (preview_url) is purely from server-side,
we can use sample image (sample_url) as the thumbnail but it's closer to original file (file_url), which will hurts both data usage, battery life, and scrolling performance.

I'll stick with preview_url that booru servers already intended to.

**Comment by nullxception** [comment]
> > I'll stick with preview_url that booru servers already intended to.
> 
> atleast add option to switch to sample_url and original_uri

there's already an option for it on latest version
