### ISSUE TITLE
Add arm64 to IzzyOnDroid

### ISSUE THREAD

**Issue by txyyh** [nullxception/boorusphere#21]
Now IzzyOnDroid only provide armabi-v7a ver for this app.
 If it's possible to contact Izzy to add arm64-v8a ver on IzzyOnDroid?

**Comment by nullxception** [comment]
Looks like it's more of F-Droid limitation* rather than IzzyOnDroid, and most likely they choose armeabi-v7a due to wider support (like x86 via arm emulation support)

Link: https://forum.f-droid.org/t/does-f-droid-allow-building-architecture-specific-apks/16734/2

**Comment by txyyh** [comment]
In fact, F-Droid support multiple architecture apks ( look at [this app on F-Droid](https://f-droid.org/zh_Hans/packages/org.mozilla.fennec_fdroid/))
F-Droid official client will choose the best architecture to install, most third-party client even can show the architecture in download section.
Deploy it is easy too. Just put multiple apks in /fdroid/repo, then `fdroid update` will solve it automatically, [just like this](https://github.com/Ehviewer-Overhauled/fdroid-repo).

So it's possible and also not difficult to implement it.

**Comment by nullxception** [comment]
> In fact, F-Droid repo support multiple architecture apks ( look at [this app on F-Droid](https://f-droid.org/zh_Hans/packages/org.mozilla.fennec_fdroid/)) F-Droid official client will choose the best architecture to install, most third-party client even can show the architecture in download section. Deploy it is easy too. Just put multiple apks in /fdroid/repo, then `fdroid update` will solve it automatically, [just like this](https://github.com/Ehviewer-Overhauled/fdroid-repo).
> 
> So it's possible and also not difficult to implement it.

Cool! though for now I don't have any plans to make an F-Droid repo as personally I don't use it.
