### ISSUE TITLE
[Feature Request] Request for Muzei Support

### ISSUE THREAD

**Issue by rsmyst** [nullxception/boorusphere#24]
Hi dev! The app is really good for going through boorus so i was wondering if support for Muzei, an automatic wallpaper app, could be added. 
Just to be clear, I am talking about [this app](https://github.com/muzei/muzei), which allows addition of "extentions" as sources for wallpaper. It has an API you can potentially use to add this functionality though I am not aware how easy or hard that would be. 
Overall a really nice app though, it's very slick.

**Comment by nullxception** [comment]
Cool things, but looks like Muzei API is only for native android app, not flutter.
