### ISSUE TITLE
Download issue 

### ISSUE THREAD

**Issue by LuciferxR** [nullxception/boorusphere#26]
Not download in storage please fix .

**Comment by nullxception** [comment]
what is your android version and app version ?

**Comment by LuciferxR** [comment]
Android 10 
App version 1.1.8

**Comment by nullxception** [comment]
> Android 10 App version 1.1.8

tested on Android 10 and working fine
![image](https://user-images.githubusercontent.com/58150791/190889724-e761a868-adbd-49fc-afe9-4e11eafb3a70.png)


Maybe you can check storage permission on app info and enable it if it disabled
![image](https://user-images.githubusercontent.com/58150791/190889790-cacc722c-4cca-4445-be3e-bac994d3ff38.png)
