### ISSUE TITLE
Preload some window around current image (even just next and previous image)

### ISSUE THREAD

**Issue by magnus-ISU** [nullxception/boorusphere#28]
This would be nice, as it would mostly remove any delay from displaying the thumbnail preview before getting the full image.

**Comment by nullxception** [comment]
I'm not sure how to do it though, but it's a good idea.

**Comment by magnus-ISU** [comment]
I could try to take a look, though I don't know flutter very well at all. Is there a data structure where it caches image results?

**Comment by nullxception** [comment]
> I could try to take a look, though I don't know flutter very well at all. Is there a data structure where it caches image results?

none, currently we're just passing the image url, so caching is automatically handled by ExtendedImage 
https://github.com/nullxception/boorusphere/blob/2b82469878e6aad2d4f1e546d94a69d277025e1f/lib/screens/post/post_image.dart#L78-L80

**Comment by magnus-ISU** [comment]
Here's a (really bad) article: https://educity.app/flutter/the-right-way-to-preload-or-precache-images-in-flutter-for-extreme-fast-rendering

Here's the documentation about the function: https://api.flutter.dev/flutter/widgets/precacheImage.html

Looking at the code, it looks to me like maybe you need to call this at line 58 for each image you want to precache (for testing could just be the next one).

I'm not sure also whether it makes useless network requests if you call `precacheImage` a bunch of times. You might want to check and make sure you haven't already loaded that image before you request it.

I'm not sure where the url for the image is coming from in your code (`post.imageFile`?), so I don't know exactly how you would do it. I also don't have a flutter dev environment set up, so I might not get to this today.

**Comment by nullxception** [comment]
> Here's the documentation about the function: https://api.flutter.dev/flutter/widgets/precacheImage.html

Nice find! I think we can use `precacheImage()` on the PageView's `onPageChanged`.
I'll try it when free 👍

The first one is indeed more of a hacks to different problem tho
