### ISSUE TITLE
Change Fav button icon color to white

### ISSUE THREAD

**Issue by sbstratos79** [nullxception/boorusphere#29]
The fav button icon is black unlike the other 3 buttons next to it. It's virtually invisible on images that don't fill up the entire screen to provide contrast for the button.
![Screenshot_20220923-122741_Boorusphere.png](https://user-images.githubusercontent.com/4395586/191907370-64d10d9b-e77f-42c8-b530-d13036c1ca80.png)

**Comment by nullxception** [comment]
fixed on https://github.com/nullxception/boorusphere/commit/9722a80a1d13338caeb60496202646d35d4d1566
