### ISSUE TITLE
Scrolling in blocked tags not working

### ISSUE THREAD

**Issue by CodeSpoof** [nullxception/boorusphere#3]
If i try to scroll through my blocked tags, it shows the signs, that i cant scroll up because im at the top, but i can't scroll down at all, no matter how many blocked tags i have.
Android 9
HTC Desire 19+
Latest version (1.0.4)

**Comment by nullxception** [comment]
> 
> 
> If i try to scroll through my blocked tags, it shows the signs, that i cant scroll up because im at the top, but i can't scroll down at all, no matter how many blocked tags i have.
> Android 9
> HTC Desire 19+
> Latest version (1.0.4)

I wasn't aware about that before, Thanks for reporting it!
