### ISSUE TITLE
how to add sankaku and sankaku idol

### ISSUE THREAD

**Issue by MakuSensei** [nullxception/boorusphere#32]
Hello I have tried to add sankaku and it doesn't work. I don't know if this application has support or I don't know what configuration to put.

**Comment by nullxception** [comment]
I think it's https://iapi.sankakucomplex.com and https://capi-v2.sankakucomplex.com
but I believe they have some kind of protection like rate limit or headers so most likely it will not working flawlessly without additional modification

**Comment by MakuSensei** [comment]
thank you

**Comment by nullxception** [comment]
> flexbooru app supports https://capi-v2.sankakucomplex.com and it works fine

great, but please don't OOT on issues.

**Comment by nullxception** [comment]
> flexbooru app supports https://capi-v2.sankakucomplex.com and it works fine

feel free to open a pull request anytime you have the fix :)

**Comment by cather37** [comment]
Server query setup e621 no longer finds (video), but thanks for the solution here:
https://github.com/nullxception/boorusphere/issues/44#issuecomment-1336130472

https://user-images.githubusercontent.com/119726134/205437489-fb6122ab-ca6c-464d-9ea4-ba8b880ec4e4.mp4

**Comment by kyoyacchi** [comment]
@nullxception This one has Sankaku support and it also coded in Dart
https://github.com/NO-ob/LoliSnatcher_Droid

**Comment by nullxception** [comment]
> @nullxception This one has Sankaku support and it also coded in Dart https://github.com/NO-ob/LoliSnatcher_Droid

Cool, but I think you mentioned wrong person, I don't browse sankaku.

**Comment by nullxception** [comment]
Closing this issues as there's no plan to add support for it.
