### ISSUE TITLE
Multilanguage support.

### ISSUE THREAD

**Issue by kyoyacchi** [nullxception/boorusphere#34]
Hi. I think it would be good to have other languages in apps other than English. I can translate Turkish for you if you want, of course.

To be honest, it took a whole time to find this app on froid, i was just floating around and come acress with this *perfect* app. It's the best booru app i've ever seen/used. 

No, i'm not "sweet-talking" here, just wanted to tell my feelings about this app.

**Comment by nullxception** [comment]
Glad you like it 😊

I also had some thoughts about it too since english isn't my main language, but I haven't learn about locale support for flutter yet, so I'll take it as note for now.
