### ISSUE TITLE
[Feature request] save tags

### ISSUE THREAD

**Issue by dill-shower** [nullxception/boorusphere#35]
Please add the function to save image's tags when downloading it to a txt file.

**Comment by nullxception** [comment]
> Please add the function to save image's tags when downloading it to a txt file.

No thanks, the downloader are supposed to downloading an image or video, nothing else.
Alternatively, you can just copy the tags to clipboard and then paste it somewhere else like notes app, or just tap the heart button to add the content to favorites library.
