### ISSUE TITLE
API key usage

### ISSUE THREAD

**Issue by CodeSpoof** [nullxception/boorusphere#4]
Maybe there could be a functionality to add your own API keys to the app to get faster results.

**Comment by nullxception** [comment]
Hi, sorry for overly late response :(

for custom api key, currently I have no interest on it,
perhaps I'll take a look for it after custom servers is added.
Thanks for the suggestion 👍

**Comment by nullxception** [comment]
API keys feature is postponed for now since I have no plan for it in short time.
