### ISSUE TITLE
Thumbnail in Main Page is extremely low quality (I can barely make out the picture)

### ISSUE THREAD

**Issue by Hekel1989** [nullxception/boorusphere#40]
Hi, as per title, it seems like the thumbnail preview is very low quality, and I can't seem to find any setting to make it better.
This happens on all the boorus I've tried (Danbooru and Safebooru).

![Screenshot_20221109-133315](https://user-images.githubusercontent.com/28776601/200843924-660c7f5f-ccf5-432a-bbdd-a68bdc2879d4.png)

This is on the latest Android 13.

Thanks

**Comment by nullxception** [comment]
booru sites is known to have low quality thumbnail (except some like konachan), there's nothing that the app can do.
