### ISSUE TITLE
Ingotnito keyboard support

### ISSUE THREAD

**Issue by ae5960e8-a6fc-491f-b252-898ecf59af95** [nullxception/boorusphere#43]
I use Gboard which supports an incognito mode in apps that request it, it will not learn new words so they are not added to the learned word list and autocomple. Reason being you don't want booru searches being stored and suggested outside the app in the keyboard.

**Comment by nullxception** [comment]
Looks like it's doable with this parameter:
https://api.flutter.dev/flutter/widgets/EditableText/enableIMEPersonalizedLearning.html

Thanks for the suggestion!

**Comment by ae5960e8-a6fc-491f-b252-898ecf59af95** [comment]
Brilliant, but the toggle is disabled upon app restart when I think it should be permanent until being disabled. Also I think it should be turned on by default.
