### ISSUE TITLE
Fix e621 access

### ISSUE THREAD

**Issue by cather37** [nullxception/boorusphere#44]
Hello, please fix e621. It says "No more result".

**Comment by nullxception** [comment]
![Screenshot_20221203-172206](https://user-images.githubusercontent.com/58150791/205436225-7d07b9ea-11c4-47c4-b488-358de86a3226.png)
hmm it works just fine on me.
make sure your server query setup is correct.

**Comment by nullxception** [comment]
here is the server queries : 

```
// Search query
posts.json?tags={tags}&page={page-id}&limit={post-limit}

// Tag suggestion query
tags.json?search[name_matches]=*{tag-part}*&search[order]=count&limit={post-limit}

// Web post query
posts/{post-id}
```

![Screenshot_20221203-172544](https://user-images.githubusercontent.com/58150791/205436360-cd18b7e5-6bcf-401e-9993-f4499a57dd55.png)
