### ISSUE TITLE
[Feature request] Improvement of android navigation bar behaviour

### ISSUE THREAD

**Issue by Palloxin** [nullxception/boorusphere#48]
https://user-images.githubusercontent.com/75091899/207061013-0c9a2850-a71a-4ef1-859c-057e26c37f63.mp4
this is how the navugation bar of android is currently handled.

https://user-images.githubusercontent.com/75091899/207059894-9a9a0809-aec5-4026-9935-bedef7ec03d0.mp4
here is how the navigation bar should be handled.
As you can see here the fullscreen is handled very well. the screenvideo is taken from an app called tachiyomi (github, open source)
OS: Android 8 miui 8
Device: huawei p8 lite 2017

**Comment by nullxception** [comment]
Full edge-to-edge support on Flutter is only present on API 29+ (Android 10 and up, Reference: https://github.com/flutter/flutter/pull/81303), otherwise, the navigation bar will behave like that.
