### ISSUE TITLE
Add flickr / own services

### ISSUE THREAD

**Issue by CodeSpoof** [nullxception/boorusphere#5]
As far as i know Flickr is *booru based aswell, not fitting into anime, but since booru is open source, there are so much of them, maybe one should be able to add their own services.
(A lot of work, I know, but im just getting into dart, sorry)

**Comment by nullxception** [comment]
Yes I've been thinking the same thing, it'd be very nice to have custom server/services.
But sadly the current api are still very hardcoded and need so much further work to make custom server easy for users.

**Comment by nate-moo** [comment]
Maybe to start you could work on adding a plugin type system where one would code a plugin which contained logic for the specific booru type or site. 

The type could then be extended to support multiple different sites using the types. 

But I don't know any dart or flutter so I wouldn't know where to start

**Comment by nullxception** [comment]
> Maybe to start you could work on adding a plugin type system where one would code a plugin which contained logic for the specific booru type or site.
> 
> The type could then be extended to support multiple different sites using the types.
> 
> But I don't know any dart or flutter so I wouldn't know where to start

ah, I prefer that user can just type the url and done, in fact, I already implemented the scanning method : https://github.com/nullxception/boorusphere/commit/f1140e17b0e24c1698bfc9715f3ee7bbdc2e434a, it just I don't have a time to working on it right now.
