### ISSUE TITLE
[Bug] "Hide downloaded media" doesn't work

### ISSUE THREAD

**Issue by Palloxin** [nullxception/boorusphere#50]
https://user-images.githubusercontent.com/75091899/207065210-c7f95edf-ea95-4b1f-acb0-ee5a38541cfd.mp4

i granted storage permission to the app despite it didn't ask for it but the feature still doesn't work
Android 8, miui 8
Huawei p8 lite 2017

**Comment by Palloxin** [comment]
Question: does this feature hide cache? when the app loads images these are technically downloaded somewhere in my phone so does this feature hide them?

**Comment by Palloxin** [comment]
If the feature not working is normal for some reason, inform the user of the said reason

**Comment by nullxception** [comment]
> i granted storage permission to the app despite it didn't ask for it but the feature still doesn't work Android 8, miui 8 Huawei p8 lite 2017

Thanks, I will look into it.
Maybe if it's buggy on some os version and cannot be fixed, then better be removed.

> Question: does this feature hide cache? when the app loads images these are technically downloaded somewhere in my phone so does this feature hide them?

It lives on app cache (/data/data/io.chaldeaprjkt.boorusphere/cache, only accessible if you're rooted), so it's hidden by default.
