### ISSUE TITLE
[Bug] very long images are of very low quality on the "preview"

### ISSUE THREAD

**Issue by Palloxin** [nullxception/boorusphere#51]
**NSFW Warning
NSFW Warning**
**NSFW Warning
NSFW Warning**

https://user-images.githubusercontent.com/75091899/207067693-0e5f90f6-75b2-495e-bbd4-95079622203c.mp4

NSFW Warning
NSFW Warning
As you can see the quality of the preview of very long images are awful.
the server is Allthefallen

**Comment by Palloxin** [comment]
Seems the pixels are kinda diluted so the result is awful

**Comment by nullxception** [comment]
I'm thinking about limiting the height of those thumbnail (maybe 2x of the width, or something like that), do you have any opinion on this matter?
