### ISSUE TITLE
[Feature Request] A way to offset x results

### ISSUE THREAD

**Issue by Palloxin** [nullxception/boorusphere#54]
Sometimes i just need to jump x results/images because i already saw them so i would like a way to do so.

**Comment by nullxception** [comment]
Sorry again, it's not possible due to app architecture decision (infinite pagination instead of numbered pagination style timeline).

**Comment by Palloxin** [comment]
> Sorry again, it's not possible due to app architecture decision (infinite pagination instead of numbered pagination style timeline).

can't it load infinitely in background (not visually displayed) until the (lets say) 2005th image is loaded? in that moment from the 2005th the app should display images, no? let me know
