### ISSUE TITLE
[Aesthetic flaw] Android navigation bar doesn't change color according to the theme chosen

### ISSUE THREAD

**Issue by Palloxin** [nullxception/boorusphere#58]
https://user-images.githubusercontent.com/75091899/207088947-e954e89d-670f-47d2-b05f-bf610c27b288.mp4

It is not pleasant to the eyes if the navigation bar of android is pitch black all the time

**Comment by nullxception** [comment]
https://github.com/nullxception/boorusphere/issues/48#issuecomment-1346865022
