### ISSUE TITLE
[Feature Request] Add a preload feature of the results

### ISSUE THREAD

**Issue by Palloxin** [nullxception/boorusphere#59]
I noticed that new "batches" (based on the preload number setted by the user) of results are loaded once i arrive at the end of the first "batch" or near it. I would like the app to really preload 100 results ahead of my current scrolling. I tested it.
set 3 columns on safebooru. scroll 40 results, then stop and take in mind the 40th picture (results), wait 20 seconds or more, then do a very fast scrolling until the load icon appears, then start counting the entries from bottom to above until u see the said 40th picture. i counted 60 picture until the 40th ( i set the preload to 100). So i am sure it doesn't really pre load in the way i intend so if you can implement it...

**Comment by nullxception** [comment]
Yes, there's no way to precisely load specific number of content, it's because most of the times, the parser filters out content that cannot be displayed (missing metadata like image properties or no thumbnail url, tags is blocked, etc).
That's why we add disclaimer to the option description.

**Comment by Palloxin** [comment]
I didn't mean that the app has to be precise. The thing is that after scrolling 40 pictures the app didn't try to make up for the ones i already scrolled (lets say "keeping the distance") so not really a preload of 100 results as i intended. it is fine if are preloaded 50-60-70 for the reason you said.
