### ISSUE TITLE
[Feature Request] Encryption of the cache

### ISSUE THREAD

**Issue by Palloxin** [nullxception/boorusphere#62]
Given the nature of this app, some results of certain servers and of certain types of picture are not exactly legal in some countries, so keeping them in the cache is not exactly safe for the user, even if we don't download them. Also my device main storage position is my sd card (on my android devjce i can choose internal or external storage, idk others) so it would be easy to get these images from my sd, even if deleted by the app.
It is common knowledge that files, when deleted, are just tagged as "rewritable" so the data stays there until it gets overwritten. So, can you add a way to do so please?

**Comment by Palloxin** [comment]
Authorities can root it and take it, so technically i still our business since it might affect the user. Well, if with flutter it can't be implemented, it is what it is

**Comment by nullxception** [comment]
> Authorities can root it and take it, so technically i still our business since it might affect the user. Well, if with flutter it can't be implemented, it is what it is

Well, in order to root an Android, bootloader must be unlocked, which will ended up data getting wiped out, so nobody can take nothing forcefully like that.

**Comment by Palloxin** [comment]
I am not familiar with the dynamic but isn't the wipe out just making the data rewriteable?

**Comment by nullxception** [comment]
> I am not familiar with the dynamic but isn't the wipe out just making the data rewriteable?

wiped out I mean is removed/reset. you can't unlock android bootloader without all data is being wiped, it's been like that since forever.

Indeed some device does not have locked bootloader, but that's like 7-10 years ago.
