### ISSUE TITLE
Add support for 90+ hz

### ISSUE THREAD

**Issue by infinitieunique** [nullxception/boorusphere#67]
### Type

UI improvement

### Issue

Adding support for a high refresh rate screens and dedicated option in settings to disable the 60hz lock would be much appreciated

### Feature

As more and more models (even not flagship ones) are starting to have high refresh rates this issue definitely should be taken into consideration...

### Motivation

Because I have a phone with high refresh rate

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by nullxception** [comment]
Flutter will follow the vsync signal at any rates that OS send, which what generally an android app (not games) should behave.
And it's working fine, ested on Android 13 (AOSP) on full 120fps, and 90fps cap.

![Screenshot_20221220-173108](https://user-images.githubusercontent.com/58150791/208646018-df4b856f-fdc3-4ab2-a9d8-27124fb210d4.png)

![Screenshot_20221220-173707](https://user-images.githubusercontent.com/58150791/208647196-5bebd412-6977-42a1-bda5-5708d7e0f250.png)

**Comment by nullxception** [comment]
> OnePlus 9 RT 5G (MT2111) android 11 (no way I am updating it past this version, slowness and new bloat guaranteed). All the other apps seem to be working fine with 120 hz refresh rate

Seems like ColorOS/OOS issues in general.
https://github.com/flutter/flutter/issues/35162
https://github.com/flutter/flutter/issues/78117
Perhaps there's a way to fix it without rely on flutter sdk fixes (since it's more of a vendor OS optimization issues).

**Comment by nullxception** [comment]
I'm closing this as it's more of device vendor specific optimization issues.
High refresh rate is working perfectly on pretty much every other phones (tested on Poco X3 Pro and Realme 10).
