### ISSUE TITLE
Feature: Favourite tags

### ISSUE THREAD

**Issue by User1l0** [nullxception/boorusphere#74]
### Type

Functionality

### Issue

Make able to have favourite tags

### Feature

.

### Motivation

.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by nullxception** [comment]
Similar concept already proposed at #70
