### ISSUE TITLE
Discord server 

### ISSUE THREAD

**Issue by ITSM3LMT** [nullxception/boorusphere#81]
### Type

Other

### Issue

Currently for us the community that loves this app there is no way for us to talk about and communicate with you. So as to resolve this please create a discord server.

### Feature

This is just a minor feature that doesn't change much of the app but will allow the project to thrive together with the community as it did with other apps like tachiyomi.

### Motivation

This will create a big community so as to further support you in your project 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by nullxception** [comment]
Sorry, I prefer GitHub-only simply because it's totally focused towards the development.
Issues can be easily tracked, and people can contribute directly.
I just can't participate in user-centric community like telegram or discord.
