### ISSUE TITLE
Feature: Add option to unblur automatically when opening image

### ISSUE THREAD

**Issue by TheGamer1002** [nullxception/boorusphere#82]
### Type

UI improvement

### Issue

As of now, swiping through the individual image view prompts the user every time focus is on blurred material (explicit). It also does this when tapping one from the gallery view.

### Feature

Add an option to disable that blur and prompt when in individual viewing mode, still retaining the blur in gallery view.

### Motivation

It's kinda annoying to have to hit that button every single time I'm swiping through. If something's been blurred and I tap on it, that's for a reason.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by nullxception** [comment]
nice idea👍
