### ISSUE TITLE
Try to add other website

### ISSUE THREAD

**Issue by DantherXD** [nullxception/boorusphere#83]
### Type

Other

### Bug description

I try to add https://unsplash.com/ but i couldn't, I'm kinda noob, i try to fill other queries but it didn't run, any idea if it's possible to add this website, if yes could you tell me how?
And is there a way to setup query for other website?

### Steps to reproduce

i try https://api.unsplash.com/ in api section, it didn't work. 

### Android version

12

### App version

1.2.9

### Acknowledgements

- [x] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [x] I have written a short but informative title.
- [x] I filled out all of the requested information in this issue properly.

**Comment by nullxception** [comment]
Unsplash is not a booru sites, hence it's not possible.

This app only support sites that use booru imageboards such as [danbooru](https://github.com/danbooru/danbooru) or [moebooru](https://github.com/moebooru/moebooru)
