### ISSUE TITLE
Add boorunav api

### ISSUE THREAD

**Issue by ITSM3LMT** [nullxception/boorusphere#84]
### Type

Functionality

### Issue

Booru nav is one of the apps that i use for adding favorites from different boorus. At first the app had fast development but now the app is almost dead. I and probably a lot of other users have a lot of favorites on the app. So it would be nice if we could export those into the boorusphere app.Their api is available on the website.

### Feature

This will probably allow people from booru nav to finally move onto this app.

### Motivation

Well honestly its wil bring more people to the app 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by nullxception** [comment]
Sorry, I have no plan to add support for importing app data from other apps. 
Maintaining data compatibility between different version on same app is already grinding enough.
