### ISSUE TITLE
Feature: Add 'Scan' support for the website rule34.us

### ISSUE THREAD

**Issue by Palloxin** [nullxception/boorusphere#85]
### Type

Other

### Issue

Scanning doesn't auto compile the right data so the server doesn't work on the apl

### Feature

![IMG_20230212_095619](https://user-images.githubusercontent.com/75091899/218301832-fdfed17c-23c1-49f4-98ec-f51ea02cbadf.jpg)
Make the app auto fill these empty spaces with the right credentials(?) when clicking on scan

### Motivation

I really don't know how to fill these camps making the server work on the app.

### Additional context

The website says it is based on modified Gelbooru 0.1.11

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Palloxin** [comment]
I managed to deduce the right "Web Post Query" based on other server settings but i really don't know what to insert on the other empty boxes.

**Comment by nullxception** [comment]
AFAIK Gelbooru 0.1.11 does not have any API. other booru client usually parse the HTML page directly,
and we can't do it here due to :
- missing thumbnail placeholder size (for staggered grid to work)
- need to fetch another page just to get a single post information (the data usage grows exponentiallyy)
- no tag suggestion API
- the list goes on

It just the nature of plain HTML that has much more limited information compared to actual API.

**Comment by Palloxin** [comment]
I know about another app called AnimeBoxes (generally booru clients) that does it and gets images very fast. Maybe they use other mehods and you copy that.
___
NSWF WARNING due to the nature of the example.
___

https://user-images.githubusercontent.com/75091899/218323055-ff60d393-6ea5-44b5-822e-7930a7d84c45.mp4

**Comment by nullxception** [comment]
> I know about another app called AnimeBoxes (generally booru clients) that does it and gets images very fast. Maybe they use other mehods and you copy that.

I know too and it uses HTML parsing just like what I tell you before, and not just animeboxes, but also lolisnatcher as well.

**Comment by nullxception** [comment]
I'm not going to rely on HTML parsing, period.
