### ISSUE TITLE
Feature: default option for the download button

### ISSUE THREAD

**Issue by Wjxfi** [nullxception/boorusphere#90]
### Type

Functionality

### Issue

I'm really tired of having to click this all the time.

### Feature

make a setting in the settings:
download by default...
original file / example

I'm from a translator so I'm not sure if it says "example", but you get my idea.

I'm really tired of having to click this all the time.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by nullxception** [comment]
Honestly I don't like that because it can lead to accidental click on download button basically unavoidable, but I'll add the option next time.
