### ISSUE TITLE
synchronize this

### ISSUE THREAD

**Issue by Wjxfi** [nullxception/boorusphere#91]
### Type

Functionality

### Issue

Now it takes a very long time, and with my idea it can be accelerated much faster

### Feature

![318964](https://user-images.githubusercontent.com/113500363/220204296-286c93c5-a1e9-4ad7-8d45-d04c4d79de97.jpg)

Once I have downloaded it to view it (photo), it should be cached so that I can download it immediately when I click on the button (image download button).

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by nullxception** [comment]
The underlying backend of image viewer ([extended_image](https://github.com/fluttercandies/extended_image)) and downloader ([flutter_downloader](https://github.com/fluttercommunity/flutter_downloader)) works differently, so it's impossible to "sync" them.
