### ISSUE TITLE
Bug: First 10 results are missing

### ISSUE THREAD

**Issue by Tau5** [nullxception/boorusphere#92]
### Type

Booru parser issues

### Bug description

The first 10 results (or what is set on "max content per-load" are missing (at least on rule34.xxx)

### Steps to reproduce

1. Open rule34.xxx on a web browser and make a query which returns more than 10 items
2. Set in the app "Max content per-load" to 10
3. Search the same thing on the app
4. Observe that the first 10 results are missing

### Android version

12.1

### App version

1.3.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by nullxception** [comment]
Looks like it caused by PageState._fetch() starts in page=1 instead of 0 (after e9610e9b72cae8869a023dbed34161ae140504c2 changes). Nice found.
