### ISSUE TITLE
Feature: sort content in search

### ISSUE THREAD

**Issue by HotarunIchijou** [nullxception/boorusphere#94]
### Type

Functionality

### Issue

As I can see, there's rating filter in search, so I think, sort also should be implemented here.

### Feature

It should looks like a rating one and locate in the right of this

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by nullxception** [comment]
Unfortunately there's no actual sorting API available (like order by views, downloads, etc).
There's only "order:score", but that's pretty much it, not worth implementing.
